name: service
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - anyio=4.10.0=py39h06a4308_0
  - aom=3.12.1=h7934f7d_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=25.1.0=py39hee96239_0
  - asttokens=3.0.0=py39h06a4308_0
  - async-lru=2.0.5=py39h06a4308_0
  - attrs=25.4.0=py39h06a4308_1
  - babel=2.16.0=py39h06a4308_0
  - backcall=0.2.0=pyhd3eb1b0_1
  - beautifulsoup4=4.13.5=py39h06a4308_0
  - blas=1.0=openblas
  - bleach=6.2.0=py39h06a4308_0
  - bottleneck=1.4.2=py39ha9d4c09_0
  - brotlicffi=1.0.9.2=py39hbdd6827_2
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hef5626c_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cairo=1.18.4=h44eff21_0
  - certifi=2025.10.5=py39h06a4308_0
  - cffi=2.0.0=py39h4eded50_0
  - charset-normalizer=3.4.4=py39h06a4308_0
  - comm=0.2.1=py39h06a4308_0
  - contourpy=1.2.1=py39hdb19cb5_1
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h1110e0f_3
  - dart-sass=1.59.1=ha770c72_0
  - dav1d=1.2.1=h5eee18b_0
  - debugpy=1.8.16=py39hbdd6827_0
  - decorator=5.2.1=py39h06a4308_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - deno=1.46.3=hcab8b69_0
  - deno-dom=0.1.41=h4768de7_0
  - esbuild=0.27.2=hfc2019e_0
  - exceptiongroup=1.3.0=py39h06a4308_0
  - executing=2.2.1=py39h06a4308_0
  - expat=2.7.3=h7354ed3_4
  - fontconfig=2.15.0=h2c49b7f_0
  - fonttools=4.60.1=py39hee96239_0
  - freetype=2.13.3=h4a9f257_0
  - fribidi=1.0.10=h7b6447c_0
  - gettext=0.21.0=hedfda30_2
  - graphite2=1.3.14=h295c915_1
  - h11=0.16.0=py39h06a4308_0
  - harfbuzz=10.2.0=hdfddeaa_1
  - httpcore=1.0.9=py39h06a4308_0
  - httpx=0.28.1=py39h06a4308_1
  - icu=73.1=h6a678d5_0
  - idna=3.11=py39h06a4308_0
  - importlib-metadata=8.5.0=py39h06a4308_0
  - importlib_metadata=8.5.0=hd3eb1b0_0
  - importlib_resources=6.5.2=py39h06a4308_0
  - ipykernel=6.30.1=py39h06a4308_0
  - ipython=8.15.0=py39h06a4308_0
  - ipython_pygments_lexers=1.1.1=py39h06a4308_0
  - ipywidgets=8.1.7=py39h06a4308_0
  - jansson=2.14=h5eee18b_1
  - jedi=0.19.2=py39h06a4308_0
  - jinja2=3.1.6=py39h06a4308_0
  - jpeg=9f=h5ce9db8_0
  - json5=0.9.25=py39h06a4308_0
  - jsonschema=4.25.0=py39h06a4308_0
  - jsonschema-specifications=2023.7.1=py39h06a4308_0
  - jupyter=1.1.1=py39h06a4308_0
  - jupyter-lsp=2.2.5=py39h06a4308_0
  - jupyter_client=8.6.3=py39h06a4308_0
  - jupyter_console=6.6.3=py39h06a4308_0
  - jupyter_core=5.8.1=py39h06a4308_0
  - jupyter_events=0.12.0=py39h06a4308_0
  - jupyter_server=2.16.0=py39h06a4308_0
  - jupyter_server_terminals=0.5.3=py39h06a4308_0
  - jupyterlab=4.4.7=py39h06a4308_0
  - jupyterlab_pygments=0.3.0=py39h06a4308_0
  - jupyterlab_server=2.28.0=py39h06a4308_0
  - jupyterlab_widgets=3.0.15=py39h06a4308_0
  - kiwisolver=1.4.4=py39h6a678d5_0
  - lcms2=2.17=heab6991_0
  - ld_impl_linux-64=2.44=h153f514_2
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20250127.0=cxx17_h6a678d5_0
  - libavif=1.3.0=h3539ee5_0
  - libcups=2.4.15=hbe4054b_0
  - libcurl=8.17.0=hc93bc37_0
  - libdeflate=1.22=h5eee18b_0
  - libdrm=2.4.124=h5eee18b_0
  - libedit=3.1.20230828=h5eee18b_0
  - libegl=1.7.0=h5eee18b_2
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libexpat=2.7.3=h7354ed3_4
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgfortran=15.2.0=h166f726_7
  - libgfortran-ng=15.2.0=h166f726_7
  - libgfortran5=15.2.0=hc633d37_7
  - libgl=1.7.0=h5eee18b_2
  - libglib=2.84.2=h37c7471_0
  - libglvnd=1.7.0=h5eee18b_2
  - libglx=1.7.0=h5eee18b_2
  - libgomp=15.2.0=h4751f2c_7
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.8=hf80d704_0
  - libkrb5=1.21.3=h520c7b4_4
  - libllvm15=15.0.7=he89c38a_4
  - libnghttp2=1.67.1=h697f920_0
  - libnsl=2.0.0=h5eee18b_0
  - libopenblas=0.3.30=h46f56fc_2
  - libopenjpeg=2.5.4=hee96239_1
  - libpciaccess=0.18=h5eee18b_0
  - libpng=1.6.50=h2ed474d_0
  - libpq=17.6=ha51bf15_0
  - libprotobuf=5.29.3=h3cdef7c_1
  - libsodium=1.0.20=heac8642_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libtiff=4.7.1=h029b1ac_0
  - libunistring=1.3=hb25bd0a_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.6.0=hb7bb969_0
  - libxcb=1.17.0=h9b100fa_0
  - libxkbcommon=1.9.1=h69220b7_0
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb25bd0a_0
  - lmdb=0.9.31=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=3.0.2=py39h5eee18b_0
  - matplotlib=3.9.2=py39h06a4308_1
  - matplotlib-base=3.9.2=py39hbfdbfaf_1
  - matplotlib-inline=0.1.7=py39h06a4308_0
  - mesalib=25.1.5=h31e3550_0
  - mistune=3.1.2=py39h06a4308_0
  - mysql=8.4.0=h721767e_2
  - nb_conda_kernels=2.5.1=pyh707e725_2
  - nbclient=0.10.2=py39h06a4308_0
  - nbconvert=7.16.6=py39h06a4308_0
  - nbconvert-core=7.16.6=py39h06a4308_0
  - nbconvert-pandoc=7.16.6=py39h06a4308_0
  - nbformat=5.10.4=py39h06a4308_0
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=py39h06a4308_0
  - notebook=7.4.5=py39h06a4308_0
  - notebook-shim=0.2.4=py39h06a4308_0
  - numexpr=2.10.1=py39hd28fd6d_0
  - numpy=2.0.2=py39hc213724_2
  - numpy-base=2.0.2=py39hf387b04_2
  - openjpeg=2.5.4=h4e0627c_1
  - openldap=2.6.10=he9288cc_1
  - openssl=3.6.0=h26f9b46_0
  - overrides=7.4.0=py39h06a4308_0
  - packaging=25.0=py39h06a4308_1
  - pandas=2.3.3=py39h505adc9_0
  - pandoc=3.6.3=ha770c72_0
  - pandocfilters=1.5.1=py39h06a4308_0
  - parso=0.8.4=py39h06a4308_0
  - pcre2=10.42=hebb0a14_1
  - pexpect=4.9.0=py39h06a4308_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=11.3.0=py39hb1c3d2d_0
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h7934f7d_0
  - platformdirs=4.3.7=py39h06a4308_0
  - prometheus_client=0.21.1=py39h06a4308_0
  - prompt-toolkit=3.0.52=py39h06a4308_1
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - psutil=7.0.0=py39hee96239_1
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd3eb1b0_3
  - pure_eval=0.2.3=py39h06a4308_0
  - pycparser=2.23=py39h06a4308_0
  - pygments=2.19.1=py39h06a4308_0
  - pyparsing=3.2.0=py39h06a4308_0
  - pyqt=6.7.1=py39h8dad735_2
  - pyqt6-sip=13.9.1=py39h6ce4db3_2
  - pysocks=1.7.1=py39h06a4308_1
  - python=3.9.25=h0dcde21_1
  - python-dateutil=2.9.0post0=py39h06a4308_2
  - python-fastjsonschema=2.20.0=py39h06a4308_0
  - python-json-logger=3.2.1=py39h06a4308_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - pytz=2025.2=py39h06a4308_0
  - pyyaml=6.0.2=py39h5eee18b_0
  - pyzmq=27.1.0=py39hcf8288c_0
  - qtbase=6.7.3=h10a5587_4
  - qtconsole=5.7.0=py39h06a4308_0
  - qtdeclarative=6.7.3=h7934f7d_1
  - qtpy=2.4.3=py39h06a4308_0
  - qtsvg=6.7.3=he4bddd1_1
  - qttools=6.7.3=h5a8de97_1
  - qtwebchannel=6.7.3=h7934f7d_1
  - qtwebsockets=6.7.3=h7934f7d_1
  - quarto=1.7.33=ha770c72_0
  - readline=8.3=hc2a1206_0
  - referencing=0.30.2=py39h06a4308_0
  - requests=2.32.5=py39h06a4308_0
  - rfc3339-validator=0.1.4=py39h06a4308_0
  - rfc3986-validator=0.1.1=py39h06a4308_0
  - rpds-py=0.22.3=py39h4aa5aa6_0
  - send2trash=1.8.2=py39h06a4308_1
  - setuptools=72.1.0=py39h06a4308_0
  - sip=6.10.0=py39h6a678d5_0
  - six=1.17.0=py39h06a4308_0
  - sniffio=1.3.0=py39h06a4308_0
  - soupsieve=2.5=py39h06a4308_0
  - spirv-tools=2025.1=hdb19cb5_0
  - sqlite=3.51.1=he0a8d7e_0
  - stack_data=0.6.3=py39h06a4308_0
  - terminado=0.18.1=py39h06a4308_0
  - tinycss2=1.4.0=py39h06a4308_0
  - tk=8.6.15=h54e0aa7_0
  - tomli=2.2.1=py39h06a4308_0
  - tornado=6.5.1=py39h5eee18b_0
  - traitlets=5.14.3=py39h06a4308_0
  - typing-extensions=4.15.0=py39h06a4308_0
  - typing_extensions=4.15.0=py39h06a4308_0
  - typst=0.13.0=h53e704d_0
  - tzdata=2025b=h04d1e81_0
  - urllib3=2.5.0=py39h06a4308_0
  - wcwidth=0.2.13=py39h06a4308_0
  - webencodings=0.5.1=py39h06a4308_1
  - websocket-client=1.8.0=py39h06a4308_0
  - wheel=0.45.1=py39h06a4308_0
  - widgetsnbextension=4.0.14=py39h06a4308_0
  - xcb-util=0.4.1=h5eee18b_2
  - xcb-util-cursor=0.1.5=h5eee18b_0
  - xcb-util-image=0.4.0=h5eee18b_2
  - xcb-util-keysyms=0.4.1=h5eee18b_0
  - xcb-util-renderutil=0.3.10=h5eee18b_0
  - xcb-util-wm=0.4.2=h5eee18b_0
  - xkeyboard-config=2.44=h382ed1a_1
  - xorg-libice=1.1.2=h9b100fa_0
  - xorg-libsm=1.2.6=h9b100fa_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxfixes=6.0.1=h9b100fa_0
  - xorg-libxrandr=1.5.4=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-libxshmfence=1.3.3=h9b100fa_0
  - xorg-libxxf86vm=1.1.6=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=hb0a5e54_1
  - zipp=3.21.0=py39h06a4308_0
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
prefix: /home/acb/miniconda3/envs/service
